// File : 032
// name : src/core/032_rnd_NoImageTexturePolicy.js
// description : Policy enforcement module that guarantees the anime lighting
//               stack NEVER depends on image textures (PNG / JPG / WebP /
//               KTX / DDS / HDR / EXR / Basis / ASTC / any bitmap format).
//               The entire visual identity is generated procedurally:
//               colors from the palette tables (016_rnd_Config.js + 019/020
//               profiles), gradients from shader math, noise from GLSL
//               functions, normals from geometry + quantization, occlusion
//               from algorithms, sky from scattering math. This module
//               audits the runtime to enforce that invariant and reports
//               violations before they reach the GPU.
//
//               Why this policy exists for Android mobile:
//                 • Zero image decode on the main thread — no jank from
//                   `new Image()` + canvas → texture upload.
//                 • Zero GPU memory spent on bitmaps — RT pool + geometry
//                   get the whole budget.
//                 • Zero network requests — no CDN stalls, no cache misses,
//                   no "texture not loaded yet" race conditions.
//                 • Deterministic boot: the engine is ready the moment
//                   shaders compile, no async texture-wait phase.
//                 • Deterministic look: the anime style is derived from
//                   numbers, not from pre-baked bitmaps, so it is
//                   resolution-independent and device-independent.
//                 • Smaller bundle: no image assets to ship, no atlas.
//
//               What counts as a violation:
//                 • `THREE.Texture` whose `image` is an HTMLImageElement,
//                   HTMLCanvasElement, HTMLVideoElement, ImageBitmap,
//                   OffscreenCanvas, or any object with `.width`/`.height`
//                   that is NOT a DataTexture or a derived procedural source.
//                 • `THREE.DataTexture` whose data is a bitmap payload
//                   (i.e. cloned from an image source). Allowed only if
//                   its `.userData.__procedural` flag is `true`.
//                 • `THREE.CompressedTexture` — always a violation
//                   (compressed textures are inherently bitmap-sourced).
//                 • `THREE.CubeTexture` built from image faces.
//                 • `THREE.TextureLoader`, `THREE.ImageLoader`,
//                   `THREE.CubeTextureLoader`, `THREE.HDRLoader`,
//                   `THREE.EXRLoader`, `THREE.RGBELoader`, `THREE.KTXLoader`,
//                   `THREE.DDSLoader`, `THREE.BasisTextureLoader` — the
//                   mere existence of these on the THREE namespace is
//                   flagged at boot (it means someone imported them).
//                 • Any `material.map`, `material.normalMap`,
//                   `material.roughnessMap`, `material.metalnessMap`,
//                   `material.emissiveMap`, `material.aoMap`,
//                   `material.alphaMap`, `material.envMap`,
//                   `material.lightMap`, `material.bumpMap`,
//                   `material.displacementMap`, `material.specularMap`
//                   that points to a bitmap-backed texture.
//
//               What is allowed:
//                 • `THREE.DataTexture` created with `userData.__procedural`
//                   = true (procedural palette LUTs, procedural noise LUTs,
//                   procedural gradient LUTs generated by CPU-side code).
//                 • `THREE.DataArrayTexture` with the same flag (for 3D LUTs
//                   used by color grading / GI probe grids).
//                 • `THREE.CanvasTexture` ONLY if its `userData.__procedural`
//                   is true AND its canvas was created from procedural math
//                   (no drawImage of an image source).
//                 • `THREE.WebGLRenderTarget.texture` — GPU-generated, not
//                   bitmap, and always allowed.
//                 • `THREE.DepthTexture` — allowed.
//
//               Enforcement modes:
//                 • AUDIT      — passive scan, records violations, no throw
//                 • WARN       — scan + log warning per violation
//                 • ENFORCE    — scan + throw on first violation
//                 • PARANOID   — scan at boot AND every N frames
//
//               The module exposes:
//                 • `markProcedural(texture)`   — flag a texture as
//                                                 procedurally generated
//                 • `isProcedural(texture)`     — query the flag
//                 • `auditThreeNamespace()`     — boot audit of THREE
//                 • `auditMaterial(material)`   — per-material scan
//                 • `auditScene(scene)`         — full scene traversal
//                 • `enforceNoImageTextures()`  — engine boot hook
//
//               All audits run OFF the per-frame hot path (boot + on-demand
//               from debug). Zero per-frame allocations on the render loop.
//
//               Strictly Three.js r185 lights only; strictly bitECS 0.4.0 API
//               only; no external policy libs; no image textures ever.
// best for : Guaranteeing on Android that the anime lighting stack never
//            allocates bitmap GPU memory, never waits on image decode,
//            and never accidentally ships an image dependency. The visual
//            quality comes from math, palette tables, and shader composition
//            — not from pre-baked bitmaps.
// License : GPL-3.0
// A new version using the https://github.com/PubDeer/astro-loop/tree/main

import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.185.0/build/three.module.js';

import {
  getPerfTier,
} from './008_scn_world.js';

import {
  getDefaultLogger,
  LOG_CHANNEL,
} from './026_rnd_Logger.js';

import {
  getDefaultProfiler,
} from './024_rnd_Profiler.js';

import {
  getDefaultErrorBoundaries,
} from './030_rnd_ErrorBoundary.js';

/* ------------------------------------------------------------------ */
/* 0. CONSTANTS                                                       */
/* ------------------------------------------------------------------ */

const PERF_TIER_LOCAL = getPerfTier();

export const POLICY_MODE = Object.freeze({
  AUDIT:    0,
  WARN:     1,
  ENFORCE:  2,
  PARANOID: 3,
});

export const POLICY_MODE_NAME = Object.freeze([
  'audit',
  'warn',
  'enforce',
  'paranoid',
]);

export const VIOLATION_KIND = Object.freeze({
  UNKNOWN:           0,
  LOADER_PRESENT:    1,
  HTML_IMAGE_TEXTURE:2,
  CANVAS_TEXTURE:    3,
  IMAGE_BITMAP:      4,
  VIDEO_TEXTURE:     5,
  COMPRESSED:        6,
  CUBE_FROM_IMAGES:  7,
  MATERIAL_MAP:      8,
  ENV_MAP:           9,
  DATA_TEXTURE_UNMARKED: 10,
  PMREM_UNMARKED:    11,
  COUNT:             12,
});

export const VIOLATION_KIND_NAME = Object.freeze([
  'unknown',
  'loader_present',
  'html_image_texture',
  'canvas_texture',
  'image_bitmap',
  'video_texture',
  'compressed',
  'cube_from_images',
  'material_map',
  'env_map',
  'data_texture_unmarked',
  'pmrem_unmarked',
]);

export const MAX_VIOLATIONS =
  PERF_TIER_LOCAL === 'HIGH'   ? 64 :
  PERF_TIER_LOCAL === 'MEDIUM' ? 48 :
                                 32;

/**
 * The material map slots that must never point at a bitmap texture.
 */
const FORBIDDEN_MATERIAL_MAP_SLOTS = Object.freeze([
  'map',
  'normalMap',
  'bumpMap',
  'roughnessMap',
  'metalnessMap',
  'emissiveMap',
  'aoMap',
  'alphaMap',
  'lightMap',
  'envMap',
  'displacementMap',
  'specularMap',
  'clearcoatMap',
  'clearcoatNormalMap',
  'clearcoatRoughnessMap',
  'iridescenceMap',
  'iridescenceThicknessMap',
  'sheenColorMap',
  'sheenRoughnessMap',
  'transmissionMap',
  'thicknessMap',
  'anisotropyMap',
]);

/**
 * Loader classes on the THREE namespace that imply bitmap usage. If any of
 * these exist on the loaded THREE namespace, either the wrong import-map
 * was configured or a subsystem is attempting to load bitmaps.
 */
const FORBIDDEN_LOADER_NAMES = Object.freeze([
  'TextureLoader',
  'ImageLoader',
  'CubeTextureLoader',
  'RGBELoader',
  'EXRLoader',
  'HDRLoader',
  'KTXLoader',
  'KTX2Loader',
  'DDSLoader',
  'PVRLoader',
  'BasisTextureLoader',
  'CompressedTextureLoader',
  'TGALoader',
  'PDBLoader',
  'MTLLoader',
  'FBXLoader',
  'GLTFLoader',
  'OBJLoader',
]);

/* ------------------------------------------------------------------ */
/* 1. HELPERS                                                         */
/* ------------------------------------------------------------------ */

const PROCEDURAL_FLAG = '__procedural';
const PROCEDURAL_SOURCE = '__proceduralSource';

function _now() {
  return (typeof performance !== 'undefined' && typeof performance.now === 'function')
    ? performance.now()
    : Date.now();
}

function _isTexture(obj) {
  return !!obj && (obj.isTexture === true || obj.isCompressedTexture === true || obj.isCubeTexture === true);
}

function _isDataTexture(obj) {
  return !!obj && obj.isDataTexture === true;
}

function _isDataArrayTexture(obj) {
  return !!obj && obj.isDataArrayTexture === true;
}

function _isCubeTexture(obj) {
  return !!obj && obj.isCubeTexture === true;
}

function _isCompressedTexture(obj) {
  return !!obj && obj.isCompressedTexture === true;
}

function _isCanvasTexture(obj) {
  return !!obj && obj.isCanvasTexture === true;
}

function _isRenderTargetTexture(obj) {
  return !!obj && obj.isRenderTargetTexture === true;
}

function _isDepthTexture(obj) {
  return !!obj && obj.isDepthTexture === true;
}

function _isPMREM(obj) {
  return !!obj && obj.isPMREMGenerator === true;
}

function _isProceduralFlagged(obj) {
  if (!obj) return false;
  const ud = obj.userData;
  if (!ud) return false;
  if (ud[PROCEDURAL_FLAG] === true) return true;
  return false;
}

/* ------------------------------------------------------------------ */
/* 2. VIOLATION RECORD                                                */
/* ------------------------------------------------------------------ */

export class ViolationRecord {
  constructor() {
    this.kind       = VIOLATION_KIND.UNKNOWN;
    this.label      = null;
    this.object     = null;
    this.details    = null;
    this.frame      = 0;
    this.timeMs     = 0;
  }

  reset() {
    this.kind    = VIOLATION_KIND.UNKNOWN;
    this.label   = null;
    this.object  = null;
    this.details = null;
    this.frame   = 0;
    this.timeMs  = 0;
    return this;
  }
}

/* ------------------------------------------------------------------ */
/* 3. NO-IMAGE POLICY ENFORCER                                        */
/* ------------------------------------------------------------------ */

export class NoImageTexturePolicy {
  constructor(options = {}) {
    this.options = Object.assign({
      mode:              POLICY_MODE.WARN,
      channel:           LOG_CHANNEL.CORE,
      logViolations:     true,
      recordProfilerMark:true,
      throwOnViolation:  false,
      maxViolations:     MAX_VIOLATIONS,
      paranoidIntervalFrames: 600,
      allowCompressed:   false,
      allowCanvasTexture:false,
      allowPMREM:        true,
    }, options || {});

    this.mode   = this.options.mode;

    this.violations = new Array(this.options.maxViolations);
    for (let i = 0; i < this.options.maxViolations; i++) this.violations[i] = new ViolationRecord();
    this.violationHead  = 0;
    this.violationCount = 0;
    this.violationTotal = 0;

    this.auditCount       = 0;
    this.auditSceneCount  = 0;
    this.auditMaterialCount = 0;
    this.auditTextureCount  = 0;

    this.frame = 0;
    this.lastParanoidFrame = -1;

    this._listeners = new Map();

    this._boundary = null;
    if (this.options.throwOnViolation) {
      try {
        const mgr = getDefaultErrorBoundaries();
        if (mgr) {
          this._boundary = mgr.create('policy.no_image_texture', {
            tag: 12 /* BOUNDARY_TAG.REGISTRY */,
            failureThreshold: 1,
          });
        }
      } catch (_) { /* swallow */ }
    }
  }

  /* ---------------- events ---------------- */

  on(event, fn) {
    if (typeof event !== 'string' || typeof fn !== 'function') return () => {};
    let arr = this._listeners.get(event);
    if (!arr) { arr = []; this._listeners.set(event, arr); }
    arr.push(fn);
    return () => this.off(event, fn);
  }

  off(event, fn) {
    const arr = this._listeners.get(event);
    if (!arr) return;
    const i = arr.indexOf(fn);
    if (i >= 0) arr.splice(i, 1);
  }

  _emit(event, payload) {
    const arr = this._listeners.get(event);
    if (!arr) return;
    for (let i = 0; i < arr.length; i++) {
      try { arr[i](payload); } catch (_) { /* swallow */ }
    }
  }

  beginFrame(frameNumber) {
    this.frame = (typeof frameNumber === 'number') ? frameNumber : (this.frame + 1);

    if (this.mode === POLICY_MODE.PARANOID) {
      if ((this.frame - this.lastParanoidFrame) >= this.options.paranoidIntervalFrames) {
        this.lastParanoidFrame = this.frame;
        this._emit('paranoid-tick', { frame: this.frame });
      }
    }
  }

  /* ---------------- violation recording ---------------- */

  _record(kind, label, object, details) {
    const rec = this.violations[this.violationHead];
    rec.reset();
    rec.kind    = kind;
    rec.label   = label || VIOLATION_KIND_NAME[kind];
    rec.object  = object || null;
    rec.details = details || null;
    rec.frame   = this.frame;
    rec.timeMs  = _now();

    this.violationHead = (this.violationHead + 1) % this.options.maxViolations;
    if (this.violationCount < this.options.maxViolations) this.violationCount++;
    this.violationTotal++;

    if (this.options.logViolations && this.mode !== POLICY_MODE.AUDIT) {
      const log = getDefaultLogger();
      if (log) {
        log.warn(this.options.channel, () =>
          `[032_rnd_NoImageTexturePolicy] violation: ${VIOLATION_KIND_NAME[kind]} — ${rec.label}` +
          (details ? ` (${details})` : '')
        );
      }
    }

    if (this.options.recordProfilerMark) {
      try {
        const p = getDefaultProfiler();
        if (p) p.mark('policy_violation:' + VIOLATION_KIND_NAME[kind]);
      } catch (_) { /* swallow */ }
    }

    this._emit('violation', {
      kind:    VIOLATION_KIND_NAME[kind],
      label:   rec.label,
      details: rec.details,
      frame:   this.frame,
    });

    if (this.options.throwOnViolation && this.mode === POLICY_MODE.ENFORCE) {
      if (this._boundary) {
        this._boundary.run(() => {
          throw new Error(`[032_rnd_NoImageTexturePolicy] enforced: ${VIOLATION_KIND_NAME[kind]} — ${rec.label}`);
        });
      } else {
        throw new Error(`[032_rnd_NoImageTexturePolicy] enforced: ${VIOLATION_KIND_NAME[kind]} — ${rec.label}`);
      }
    }

    return false;
  }

  /* ---------------- procedural marking ---------------- */

  /**
   * Marks a texture (DataTexture, CanvasTexture, DataArrayTexture, or any
   * custom texture) as procedurally generated. This is the ONLY sanctioned
   * way to opt out of the bitmap policy.
   *
   *   markProcedural(myNoiseLUT, 'noise_lut');
   */
  markProcedural(texture, source) {
    if (!texture) return false;
    if (!texture.userData) texture.userData = {};
    texture.userData[PROCEDURAL_FLAG] = true;
    if (source) texture.userData[PROCEDURAL_SOURCE] = String(source);
    return true;
  }

  isProcedural(texture) {
    return _isProceduralFlagged(texture);
  }

  unmarkProcedural(texture) {
    if (!texture || !texture.userData) return false;
    delete texture.userData[PROCEDURAL_FLAG];
    delete texture.userData[PROCEDURAL_SOURCE];
    return true;
  }

  /* ---------------- texture audits ---------------- */

  /**
   * Audits a single texture. Returns true if compliant, false otherwise.
   * Non-textures return true (nothing to check).
   */
  auditTexture(texture, label) {
    if (!texture) return true;
    if (!_isTexture(texture)) return true;

    this.auditTextureCount++;

    // Allow-list: GPU-generated or engine-internal.
    if (_isRenderTargetTexture(texture)) return true;
    if (_isDepthTexture(texture))        return true;

    // PMREM-generated textures: allowed if policy permits.
    if (this.options.allowPMREM && _isProceduralFlagged(texture)) return true;

    // Compressed textures: always a violation.
    if (_isCompressedTexture(texture)) {
      if (!this.options.allowCompressed) {
        return this._record(
          VIOLATION_KIND.COMPRESSED,
          label || 'compressed texture',
          texture,
          'Compressed textures imply a bitmap source'
        );
      }
      return true;
    }

    // Cube textures: check faces.
    if (_isCubeTexture(texture)) {
      return this._auditCubeTexture(texture, label);
    }

    // Canvas textures: allowed only if marked procedural AND we've verified
    // no image source was drawn into the canvas.
    if (_isCanvasTexture(texture)) {
      if (this.options.allowCanvasTexture && _isProceduralFlagged(texture)) {
        return true;
      }
      return this._record(
        VIOLATION_KIND.CANVAS_TEXTURE,
        label || 'canvas texture',
        texture,
        'CanvasTexture requires markProcedural() + procedural-only canvas'
      );
    }

    // DataTexture: allowed only if marked procedural.
    if (_isDataTexture(texture) || _isDataArrayTexture(texture)) {
      if (_isProceduralFlagged(texture)) return true;
      return this._record(
        VIOLATION_KIND.DATA_TEXTURE_UNMARKED,
        label || 'data texture',
        texture,
        'DataTexture must be marked markProcedural()'
      );
    }

    // Regular Texture: check the .image source.
    const img = texture.image;
    if (!img) return true; // no image yet, still loading — treat as ok

    const tag = Object.prototype.toString.call(img);

    // HTMLImageElement
    if (typeof HTMLImageElement !== 'undefined' && img instanceof HTMLImageElement) {
      return this._record(
        VIOLATION_KIND.HTML_IMAGE_TEXTURE,
        label || 'html image texture',
        texture,
        'src=' + (img.src || '').slice(0, 64)
      );
    }

    // ImageBitmap
    if (typeof ImageBitmap !== 'undefined' && img instanceof ImageBitmap) {
      return this._record(
        VIOLATION_KIND.IMAGE_BITMAP,
        label || 'image bitmap texture',
        texture,
        `size=${img.width}x${img.height}`
      );
    }

    // HTMLVideoElement
    if (typeof HTMLVideoElement !== 'undefined' && img instanceof HTMLVideoElement) {
      return this._record(
        VIOLATION_KIND.VIDEO_TEXTURE,
        label || 'video texture',
        texture,
        'video is not permitted'
      );
    }

    // HTMLCanvasElement not flagged via isCanvasTexture: treat as violation.
    if (typeof HTMLCanvasElement !== 'undefined' && img instanceof HTMLCanvasElement) {
      if (_isProceduralFlagged(texture)) return true;
      return this._record(
        VIOLATION_KIND.CANVAS_TEXTURE,
        label || 'html canvas texture',
        texture,
        `size=${img.width}x${img.height}`
      );
    }

    // OffscreenCanvas
    if (typeof OffscreenCanvas !== 'undefined' && img instanceof OffscreenCanvas) {
      if (_isProceduralFlagged(texture)) return true;
      return this._record(
        VIOLATION_KIND.CANVAS_TEXTURE,
        label || 'offscreen canvas texture',
        texture,
        `size=${img.width}x${img.height}`
      );
    }

    // Unknown image-like object with width/height: treat as suspicious.
    if (typeof img === 'object' && typeof img.width === 'number' && typeof img.height === 'number') {
      if (_isProceduralFlagged(texture)) return true;
      return this._record(
        VIOLATION_KIND.UNKNOWN,
        label || 'unknown image texture',
        texture,
        tag + ' ' + img.width + 'x' + img.height
      );
    }

    return true;
  }

  _auditCubeTexture(cube, label) {
    const faces = cube.image;
    if (!faces) return true;

    // CubeTexture.image may be an array of 6 images or an array of 6
    // { image: ... } objects. Check both shapes.
    const array = Array.isArray(faces) ? faces : null;
    if (!array) return true;

    for (let i = 0; i < array.length; i++) {
      const f = array[i];
      if (!f) continue;
      const img = f.image !== undefined ? f.image : f;
      if (!img) continue;

      if (typeof HTMLImageElement !== 'undefined' && img instanceof HTMLImageElement) {
        return this._record(
          VIOLATION_KIND.CUBE_FROM_IMAGES,
          (label || 'cube texture') + ' face ' + i,
          cube,
          'src=' + (img.src || '').slice(0, 64)
        );
      }
      if (typeof HTMLCanvasElement !== 'undefined' && img instanceof HTMLCanvasElement) {
        if (!_isProceduralFlagged(cube)) {
          return this._record(
            VIOLATION_KIND.CUBE_FROM_IMAGES,
            (label || 'cube texture') + ' face ' + i,
            cube,
            'canvas face'
          );
        }
      }
      if (typeof ImageBitmap !== 'undefined' && img instanceof ImageBitmap) {
        return this._record(
          VIOLATION_KIND.CUBE_FROM_IMAGES,
          (label || 'cube texture') + ' face ' + i,
          cube,
          'image bitmap face'
        );
      }
    }
    return true;
  }

  /* ---------------- material audits ---------------- */

  /**
   * Audits a material for any forbidden map slot. Returns true if compliant.
   */
  auditMaterial(material, label) {
    if (!material) return true;
    this.auditMaterialCount++;

    let ok = true;
    for (let i = 0; i < FORBIDDEN_MATERIAL_MAP_SLOTS.length; i++) {
      const slot = FORBIDDEN_MATERIAL_MAP_SLOTS[i];
      const tex = material[slot];
      if (!tex) continue;

      const slotLabel = (label || material.name || 'material') + '.' + slot;
      if (!this.auditTexture(tex, slotLabel)) {
        ok = false;
        if (slot === 'envMap') {
          this._record(
            VIOLATION_KIND.ENV_MAP,
            slotLabel,
            material,
            'envMap must be procedural (PMREM of procedural sky)'
          );
        } else {
          this._record(
            VIOLATION_KIND.MATERIAL_MAP,
            slotLabel,
            material,
            'material.' + slot + ' must not be bitmap-backed'
          );
        }
      }
    }
    return ok;
  }

  /* ---------------- scene audits ---------------- */

  /**
   * Traverses a scene and audits every material and texture it finds.
   * Returns the number of violations discovered in this pass.
   */
  auditScene(scene, label) {
    if (!scene || typeof scene.traverse !== 'function') return 0;
    this.auditSceneCount++;

    const startViolations = this.violationTotal;

    scene.traverse((obj) => {
      if (!obj) return;

      // Material
      const mat = obj.material;
      if (mat) {
        if (Array.isArray(mat)) {
          for (let i = 0; i < mat.length; i++) {
            this.auditMaterial(mat[i], (label || 'scene') + '/' + (obj.name || 'mesh') + '[' + i + ']');
          }
        } else {
          this.auditMaterial(mat, (label || 'scene') + '/' + (obj.name || 'mesh'));
        }
      }

      // Background texture.
      if (obj === scene && scene.background) {
        if (_isTexture(scene.background)) {
          this.auditTexture(scene.background, 'scene.background');
        }
      }

      // Environment.
      if (obj === scene && scene.environment) {
        if (_isTexture(scene.environment)) {
          this.auditTexture(scene.environment, 'scene.environment');
        }
      }

      // Light shadow maps.
      if (obj.isLight && obj.shadow && obj.shadow.map) {
        // Shadow maps are render-target textures — allowed.
      }

      // Fog textures (FogExp2 / Fog have no textures).
    });

    return this.violationTotal - startViolations;
  }

  /* ---------------- namespace audits ---------------- */

  /**
   * Audits the THREE namespace for forbidden loaders. Returns the number
   * of forbidden loaders found.
   */
  auditThreeNamespace() {
    let found = 0;
    for (let i = 0; i < FORBIDDEN_LOADER_NAMES.length; i++) {
      const name = FORBIDDEN_LOADER_NAMES[i];
      if (typeof THREE[name] !== 'undefined') {
        found++;
        this._record(
          VIOLATION_KIND.LOADER_PRESENT,
          'THREE.' + name,
          THREE[name],
          'bitmap loader present on THREE namespace'
        );
      }
    }
    return found;
  }

  /* ---------------- engine boot hook ---------------- */

  /**
   * Call this once at engine boot. Audits the THREE namespace, then
   * optionally audits a scene if provided.
   */
  enforceNoImageTextures(scene) {
    this.auditCount++;
    const t0 = _now();

    const loaders = this.auditThreeNamespace();
    let sceneViolations = 0;
    if (scene) {
      sceneViolations = this.auditScene(scene, 'boot');
    }

    const t1 = _now();
    this._emit('audit-complete', {
      loaders,
      sceneViolations,
      totalViolations: this.violationTotal,
      durationMs: t1 - t0,
    });

    return {
      loaders,
      sceneViolations,
      totalViolations: this.violationTotal,
      durationMs: t1 - t0,
      ok: this.violationTotal === 0,
    };
  }

  /* ---------------- diagnostics ---------------- */

  isCompliant() {
    return this.violationTotal === 0;
  }

  getRecentViolations(max, out) {
    const n = Math.min(max | 0 || this.violationCount, this.violationCount);
    for (let i = 0; i < n; i++) {
      const idx = (this.violationHead - n + i + this.options.maxViolations) % this.options.maxViolations;
      if (out) {
        out[i] = {
          kind:    VIOLATION_KIND_NAME[this.violations[idx].kind],
          label:   this.violations[idx].label,
          details: this.violations[idx].details,
          frame:   this.violations[idx].frame,
          timeMs:  this.violations[idx].timeMs,
        };
      }
    }
    return n;
  }

  getStats() {
    return {
      mode:                 POLICY_MODE_NAME[this.mode],
      modeIndex:            this.mode,
      compliant:            this.violationTotal === 0,
      violationTotal:       this.violationTotal,
      violationRingCount:   this.violationCount,
      violationRingCap:     this.options.maxViolations,
      auditCount:           this.auditCount,
      auditSceneCount:      this.auditSceneCount,
      auditMaterialCount:   this.auditMaterialCount,
      auditTextureCount:    this.auditTextureCount,
      allowCompressed:      this.options.allowCompressed,
      allowCanvasTexture:   this.options.allowCanvasTexture,
      allowPMREM:           this.options.allowPMREM,
    };
  }

  /* ---------------- reset / dispose ---------------- */

  reset() {
    for (let i = 0; i < this.options.maxViolations; i++) this.violations[i].reset();
    this.violationHead = 0;
    this.violationCount = 0;
    this.violationTotal = 0;
    this.auditCount = 0;
    this.auditSceneCount = 0;
    this.auditMaterialCount = 0;
    this.auditTextureCount = 0;
    this.frame = 0;
    this.lastParanoidFrame = -1;
    return this;
  }

  dispose() {
    this.reset();
    this._listeners.clear();
    return this;
  }
}

/* ------------------------------------------------------------------ */
/* 4. MODULE-LEVEL SINGLETON                                          */
/* ------------------------------------------------------------------ */

let _defaultPolicy = null;

export function getDefaultNoImagePolicy() {
  if (!_defaultPolicy) _defaultPolicy = new NoImageTexturePolicy();
  return _defaultPolicy;
}

export function disposeDefaultNoImagePolicy() {
  if (_defaultPolicy) {
    _defaultPolicy.dispose();
    _defaultPolicy = null;
  }
}

/* ------------------------------------------------------------------ */
/* 5. CONVENIENCE HELPERS                                             */
/* ------------------------------------------------------------------ */

export function markProcedural(texture, source) {
  return getDefaultNoImagePolicy().markProcedural(texture, source);
}

export function isProcedural(texture) {
  return getDefaultNoImagePolicy().isProcedural(texture);
}

export function enforceNoImageTextures(scene) {
  return getDefaultNoImagePolicy().enforceNoImageTextures(scene);
}

export function auditNoImageScene(scene, label) {
  return getDefaultNoImagePolicy().auditScene(scene, label);
}

export function auditNoImageMaterial(material, label) {
  return getDefaultNoImagePolicy().auditMaterial(material, label);
}

export function auditNoImageTexture(texture, label) {
  return getDefaultNoImagePolicy().auditTexture(texture, label);
}

export function noImagePolicyBeginFrame(frameNumber) {
  getDefaultNoImagePolicy().beginFrame(frameNumber);
}

export function isNoImagePolicyCompliant() {
  return getDefaultNoImagePolicy().isCompliant();
}

/* ------------------------------------------------------------------ */
/* 6. PROCEDURAL TEXTURE FACTORIES (the sanctioned alternatives)      */
/* ------------------------------------------------------------------ */

/**
 * Creates a procedural 1D LUT texture for palette / gradient sampling.
 * The LUT is populated by the caller-supplied fill function:
 *
 *   const lut = createProceduralLUT(256, (t, r, g, b) => {
 *     r[0] = ...; g[0] = ...; b[0] = ...;
 *   });
 */
export function createProceduralLUT(size, fillFn) {
  const s = Math.max(2, size | 0);
  const data = new Uint8Array(s * 4);

  if (typeof fillFn === 'function') {
    const r = new Float32Array(1);
    const g = new Float32Array(1);
    const b = new Float32Array(1);
    for (let i = 0; i < s; i++) {
      const t = i / (s - 1);
      r[0] = 0; g[0] = 0; b[0] = 0;
      fillFn(t, r, g, b);
      const i4 = i * 4;
      data[i4]     = Math.max(0, Math.min(255, (r[0] * 255) | 0));
      data[i4 + 1] = Math.max(0, Math.min(255, (g[0] * 255) | 0));
      data[i4 + 2] = Math.max(0, Math.min(255, (b[0] * 255) | 0));
      data[i4 + 3] = 255;
    }
  }

  const tex = new THREE.DataTexture(data, s, 1, THREE.RGBAFormat);
  tex.minFilter = THREE.LinearFilter;
  tex.magFilter = THREE.LinearFilter;
  tex.wrapS = THREE.ClampToEdgeWrapping;
  tex.wrapT = THREE.ClampToEdgeWrapping;
  tex.generateMipmaps = false;
  tex.needsUpdate = true;
  markProcedural(tex, 'createProceduralLUT');
  return tex;
}

/**
 * Creates a procedural 2D noise texture (RGBA, [0,255] clamped) populated
 * by the caller-supplied fill function:
 *
 *   const noise = createProceduralNoise(128, (x, y, r, g, b) => {
 *     r[0] = ...; g[0] = ...; b[0] = ...;
 *   });
 */
export function createProceduralNoise(size, fillFn) {
  const s = Math.max(2, size | 0);
  const data = new Uint8Array(s * s * 4);

  if (typeof fillFn === 'function') {
    const r = new Float32Array(1);
    const g = new Float32Array(1);
    const b = new Float32Array(1);
    for (let y = 0; y < s; y++) {
      for (let x = 0; x < s; x++) {
        r[0] = 0; g[0] = 0; b[0] = 0;
        fillFn(x, y, r, g, b);
        const i4 = (y * s + x) * 4;
        data[i4]     = Math.max(0, Math.min(255, (r[0] * 255) | 0));
        data[i4 + 1] = Math.max(0, Math.min(255, (g[0] * 255) | 0));
        data[i4 + 2] = Math.max(0, Math.min(255, (b[0] * 255) | 0));
        data[i4 + 3] = 255;
      }
    }
  }

  const tex = new THREE.DataTexture(data, s, s, THREE.RGBAFormat);
  tex.minFilter = THREE.LinearFilter;
  tex.magFilter = THREE.LinearFilter;
  tex.wrapS = THREE.RepeatWrapping;
  tex.wrapT = THREE.RepeatWrapping;
  tex.generateMipmaps = false;
  tex.needsUpdate = true;
  markProcedural(tex, 'createProceduralNoise');
  return tex;
}

/**
 * Creates a procedurally filled Float32 DataTexture used for high-precision
 * LUTs (SH coefficients, palette in linear space, GI probe grids).
 */
export function createProceduralFloatTexture(width, height, fillFn) {
  const w = Math.max(2, width | 0);
  const h = Math.max(2, height | 0);
  const data = new Float32Array(w * h * 4);

  if (typeof fillFn === 'function') {
    const r = new Float32Array(1);
    const g = new Float32Array(1);
    const b = new Float32Array(1);
    const a = new Float32Array(1);
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        r[0] = 0; g[0] = 0; b[0] = 0; a[0] = 1;
        fillFn(x, y, w, h, r, g, b, a);
        const i4 = (y * w + x) * 4;
        data[i4]     = r[0];
        data[i4 + 1] = g[0];
        data[i4 + 2] = b[0];
        data[i4 + 3] = a[0];
      }
    }
  }

  const tex = new THREE.DataTexture(data, w, h, THREE.RGBAFormat, THREE.FloatType);
  tex.minFilter = THREE.LinearFilter;
  tex.magFilter = THREE.LinearFilter;
  tex.wrapS = THREE.ClampToEdgeWrapping;
  tex.wrapT = THREE.ClampToEdgeWrapping;
  tex.generateMipmaps = false;
  tex.needsUpdate = true;
  markProcedural(tex, 'createProceduralFloatTexture');
  return tex;
}

/**
 * Creates a procedurally filled DataArrayTexture (3D LUT) for color
 * grading, GI SH coefficients, or palette interpolation. Caller fills
 * with `fillFn(x, y, z, r, g, b, a)`.
 */
export function createProceduralDataArrayTexture(width, height, depth, fillFn) {
  const w = Math.max(2, width | 0);
  const h = Math.max(2, height | 0);
  const d = Math.max(2, depth | 0);
  const total = w * h * d * 4;
  const data = new Uint8Array(total);

  if (typeof fillFn === 'function') {
    const r = new Float32Array(1);
    const g = new Float32Array(1);
    const b = new Float32Array(1);
    const a = new Float32Array(1);
    let i4 = 0;
    for (let z = 0; z < d; z++) {
      for (let y = 0; y < h; y++) {
        for (let x = 0; x < w; x++) {
          r[0] = 0; g[0] = 0; b[0] = 0; a[0] = 1;
          fillFn(x, y, z, r, g, b, a);
          data[i4]     = Math.max(0, Math.min(255, (r[0] * 255) | 0));
          data[i4 + 1] = Math.max(0, Math.min(255, (g[0] * 255) | 0));
          data[i4 + 2] = Math.max(0, Math.min(255, (b[0] * 255) | 0));
          data[i4 + 3] = Math.max(0, Math.min(255, (a[0] * 255) | 0));
          i4 += 4;
        }
      }
    }
  }

  const tex = new THREE.DataArrayTexture(data, w, h, d);
  tex.format = THREE.RGBAFormat;
  tex.type = THREE.UnsignedByteType;
  tex.minFilter = THREE.LinearFilter;
  tex.magFilter = THREE.LinearFilter;
  tex.wrapS = THREE.ClampToEdgeWrapping;
  tex.wrapT = THREE.ClampToEdgeWrapping;
  tex.generateMipmaps = false;
  tex.needsUpdate = true;
  markProcedural(tex, 'createProceduralDataArrayTexture');
  return tex;
}

/* ------------------------------------------------------------------ */
/* 7. FACTORY                                                         */
/* ------------------------------------------------------------------ */

export function createNoImagePolicy(options = {}) {
  return new NoImageTexturePolicy(options);
}

/* ------------------------------------------------------------------ */
/* 8. DEFAULT EXPORT                                                  */
/* ------------------------------------------------------------------ */

const _defaultExport = {
  NoImageTexturePolicy,
  ViolationRecord,

  createNoImagePolicy,
  getDefaultNoImagePolicy,
  disposeDefaultNoImagePolicy,

  markProcedural,
  isProcedural,
  enforceNoImageTextures,
  auditNoImageScene,
  auditNoImageMaterial,
  auditNoImageTexture,
  noImagePolicyBeginFrame,
  isNoImagePolicyCompliant,

  createProceduralLUT,
  createProceduralNoise,
  createProceduralFloatTexture,
  createProceduralDataArrayTexture,

  POLICY_MODE,
  POLICY_MODE_NAME,
  VIOLATION_KIND,
  VIOLATION_KIND_NAME,
  FORBIDDEN_MATERIAL_MAP_SLOTS,
  FORBIDDEN_LOADER_NAMES,
  MAX_VIOLATIONS,
};

export default _defaultExport;